name: get advisories

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependency check
      run: sudo apt install g++ pkg-config libx11-dev libasound2-dev libudev-dev lld
    - name: rustup install
      run: | 
        rustup toolchain install nightly
        rustup update
        rustup default nightly
    - name: install cargo deny
      run: cargo install --locked cargo-deny
    - name: check advisories
      run: cargo deny check advisories
