name: clippy

on:
  push:
    paths:
      - '.github/workflows/clippy.yml'
      - 'src/*'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: dependency check
      run: sudo apt install g++ pkg-config libx11-dev libasound2-dev libudev-dev lld
    - name: rustup install
      run: | 
        rustup toolchain install nightly
        rustup update
        rustup default nightly
    - name: add cargo clippy
      run: rustup component add clippy
    - name: test
      run: cargo clippy
